# Generated by Django 3.0.1 on 2020-01-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0002_create_system_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrant',
            name='comment',
            field=models.TextField(blank=True, help_text='Post-race pithy comeback from the entrant', max_length=200, null=True),
        ),
    ]
