# Generated by Django 3.0.1 on 2020-01-15 08:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0003_auto_20200111_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='start_delay',
            field=models.DurationField(default=datetime.timedelta(seconds=15), help_text='How long to wait before beginning the race after everyone is ready.', validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=10)), django.core.validators.MaxValueValidator(datetime.timedelta(seconds=60))]),
        ),
    ]
