# Generated by Django 3.0.1 on 2020-01-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0005_race_allow_non_entrant_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='allow_non_entrant_chat',
            field=models.BooleanField(default=False, help_text='Allow users who are not entered in the race to chat while the race is in progress (anyone may use chat before and after the race).'),
        ),
        migrations.AlterField(
            model_name='race',
            name='custom_goal',
            field=models.CharField(blank=True, default=None, help_text='Set a custom goal for this race, if none of the category goals are suitable. <strong>Custom races cannot be recorded.</strong>', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='info',
            field=models.TextField(blank=True, help_text='Any useful information for race entrants (e.g. randomizer seed).', max_length=1000, null=True),
        ),
    ]
