# Generated by Django 3.0.2 on 2020-01-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0009_auto_20200125_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='cancelled_at',
            field=models.DateTimeField(null=True),
        ),
    ]
