# Generated by Django 3.0.2 on 2020-01-31 02:28

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0010_race_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='chat_message_delay',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The length of time chat messages display for only monitors. After this delay messages that have not been deleted will display to everyone.', validators=[django.core.validators.MinValueValidator(datetime.timedelta(0)), django.core.validators.MaxValueValidator(datetime.timedelta(seconds=90))]),
        ),
    ]
