# Generated by Django 3.0.2 on 2020-02-08 09:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from oauth2_provider.settings import oauth2_settings


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0001_initial'),
        ('racetime', '0011_race_chat_message_delay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, help_text='Public name for this bot (3-25 characters). Must be unique, and may not contain # or @ characters.', max_length=25, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(inverse_match=True, message='Name cannot contain @ or #', regex='[\\x00@#]')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=oauth2_settings.APPLICATION_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='racetime.Category')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bot',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_name_per_category'),
        ),
    ]
