# Generated by Django 3.0.2 on 2020-02-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0013_auto_20200208_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='userranking',
            name='best_time',
            field=models.DurationField(null=True),
        ),
    ]
