# Generated by Django 3.0.2 on 2020-02-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0015_auto_20200221_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='async_enabled',
            field=models.BooleanField(default=False, help_text='Enable asynchronous races in this category. Moderators can start new async races if this feature is enabled.', verbose_name='Use asynchronous races'),
        ),
    ]
