# Generated by Django 3.0.2 on 2020-03-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0016_auto_20200302_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrant',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
