# Generated by Django 3.0.2 on 2020-03-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0017_entrant_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='changed_password',
            field=models.BooleanField(default=False),
        ),
    ]
