# Generated by Django 3.0.2 on 2020-03-04 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0018_userlog_changed_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='rematch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='racetime.Race'),
        ),
    ]
