# Generated by Django 3.0.2 on 2020-03-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0019_race_rematch'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
