# Generated by Django 3.0.2 on 2020-03-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0020_race_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_from', models.DateTimeField()),
                ('visible_to', models.DateTimeField()),
                ('message', models.TextField()),
                ('class_names', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='bulletin',
            index=models.Index(fields=['visible_from', 'visible_to'], name='racetime_bu_visible_4abb78_idx'),
        ),
    ]
