# Generated by Django 3.0.5 on 2020-04-02 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0022_useraction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='ban',
            name='category',
            field=models.ForeignKey(blank=True, help_text='If left blank, ban will be site-wide.', null=True, on_delete=django.db.models.deletion.CASCADE, to='racetime.Category'),
        ),
        migrations.AlterField(
            model_name='ban',
            name='notes',
            field=models.TextField(blank=True, help_text='Describe why this ban was issued. Only visible to administrators.'),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='class_names',
            field=models.CharField(blank=True, help_text='Space-separated CSS class names, e.g. "highlight".', max_length=255),
        ),
        migrations.AlterField(
            model_name='categoryrequest',
            name='accepted_as',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='racetime.Category'),
        ),
        migrations.AlterField(
            model_name='categoryrequest',
            name='requested_by',
            field=models.ForeignKey(help_text='This user will own the category once accepted.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoryrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Grants the user full permission to manage categories on the site.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_supporter',
            field=models.BooleanField(default=False, help_text='Currently does nothing.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitch_code',
            field=models.CharField(editable=False, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitch_id',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitch_name',
            field=models.CharField(editable=False, max_length=25, null=True),
        ),
    ]
