# Generated by Django 3.0.2 on 2020-04-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0025_user_custom_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourite_categories',
            field=models.ManyToManyField(blank=True, limit_choices_to={'active': True}, related_name='_user_favourite_categories_+', to='racetime.Category'),
        ),
    ]
