# Generated by Django 3.0.2 on 2020-04-09 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0027_auto_20200408_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupporterSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start/End dates are inclusive.')),
                ('end_date', models.DateField(help_text='Start/End dates are inclusive.')),
                ('reason', models.CharField(choices=[('manual', 'Manually applied')], default='manual', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Supporters',
            },
        ),
    ]
