# Generated by Django 3.0.5 on 2020-04-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0028_supporterschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='allow_stream_override',
            field=models.BooleanField(default=False, help_text='Allow race monitors to change the streaming requirements for their race room. By default, only moderators can change this.'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('activate', 'set category to active'), ('deactivate', 'set category to inactive'), ('name_change', 'updated category name'), ('short_name_change', 'updated category short name'), ('image_change', 'updated category image'), ('info_change', 'updated category info'), ('slug_words_change', 'updated category slug words'), ('streaming_required_change', 'updated category streaming requirement'), ('allow_stream_override_change', 'updated category stream override'), ('owner_change', 'transferred category ownership'), ('moderator_add', 'added a moderator'), ('moderator_remove', 'removed a moderator'), ('bot_add', 'added a bot'), ('bot_activate', 're-activated a bot'), ('bot_deactivate', 'deactivated a bot'), ('goal_add', 'added a new goal'), ('goal_activate', 're-activated a goal'), ('goal_deactivate', 'deactivated a goal')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='race',
            name='streaming_required',
            field=models.BooleanField(default=True, help_text='Override the streaming rules for this category.'),
        ),
    ]
