# Generated by Django 3.0.2 on 2020-05-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0029_auto_20200418_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='allow_non_entrant_chat',
            field=models.BooleanField(default=True, help_text='Allow users who are not entered in the race to chat while the race is in progress (anyone may use chat before and after the race).'),
        ),
    ]
