# Generated by Django 3.0.2 on 2020-05-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0031_user_detailed_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrant',
            name='score',
        ),
        migrations.RemoveField(
            model_name='entrant',
            name='score_change',
        ),
        migrations.AddField(
            model_name='entrant',
            name='rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entrant',
            name='rating_change',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userranking',
            name='rating',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='userranking',
            name='times_raced',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='userranking',
            name='best_time',
            field=models.DurationField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='userranking',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
