# Generated by Django 3.0.2 on 2020-05-23 11:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0032_auto_20200516_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='time_limit',
            field=models.DurationField(default=datetime.timedelta(days=1), help_text='The maximum time limit for any race entrant. Entrants who have not finished in this time will be disqualified.', validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=3600)), django.core.validators.MaxValueValidator(datetime.timedelta(days=3))]),
        ),
    ]
