# Generated by Django 3.0.7 on 2020-06-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0033_auto_20200523_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('activate', 'set category to active'), ('deactivate', 'set category to inactive'), ('name_change', 'updated category name'), ('short_name_change', 'updated category short name'), ('image_change', 'updated category image'), ('info_change', 'updated category info'), ('slug_words_change', 'updated category slug words'), ('streaming_required_change', 'updated category streaming requirement'), ('allow_stream_override_change', 'updated category stream override'), ('owner_change', 'transferred category ownership'), ('moderator_add', 'added a moderator'), ('moderator_remove', 'removed a moderator'), ('bot_add', 'added a bot'), ('bot_activate', 're-activated a bot'), ('bot_deactivate', 'deactivated a bot'), ('goal_add', 'added a new goal'), ('goal_activate', 're-activated a goal'), ('goal_deactivate', 'deactivated a goal'), ('goal_rename', 'renamed a goal')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='short_name',
            field=models.CharField(db_index=True, help_text='An abbreviation or other short identifier, e.g. "SM64".', max_length=16),
        ),
        migrations.AlterField(
            model_name='categoryrequest',
            name='goals',
            field=models.TextField(help_text='Add goals, one per line, that people can race against. Goal names should be short, clear and simple, e.g. "Any%", "16 stars", or simply "Beat the game". You can add more goals later, but your category must have at least one goal to start with.'),
        ),
        migrations.AlterField(
            model_name='categoryrequest',
            name='name',
            field=models.CharField(help_text='The full name of this category, e.g. "Super Mario 64" or "Multiple Sonic Games".', max_length=255),
        ),
        migrations.AlterField(
            model_name='categoryrequest',
            name='short_name',
            field=models.CharField(help_text='An abbreviation or other short identifier, e.g. "SM64". Try to keep this under 8 characters.', max_length=16),
        ),
        migrations.AlterField(
            model_name='categoryrequest',
            name='slug',
            field=models.CharField(help_text='A unique identifier for this category used in the URL, e.g. "tetris-99". If in doubt, just put the game name in lowercase without spaces.', max_length=255),
        ),
    ]
