# Generated by Django 3.0.7 on 2020-06-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0034_auto_20200612_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrant',
            name='finish_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
