# Generated by Django 3.0.7 on 2020-06-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0036_auto_20200617_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='ban',
            name='expires_at',
            field=models.DateField(blank=True, db_index=True, help_text='Date that user may race again. If left blank, ban will be permanent.', null=True),
        ),
        migrations.AddField(
            model_name='ban',
            name='reason',
            field=models.TextField(blank=True, help_text='Visible to the USER. Give a brief explaination for the ban.'),
        ),
        migrations.AlterField(
            model_name='ban',
            name='notes',
            field=models.TextField(blank=True, help_text='Any additional detail on why this ban was issued. Only visible to administrators.'),
        ),
    ]
