# Generated by Django 3.0.8 on 2020-07-27 23:35

import django.core.validators
from django.db import migrations, models
import racetime.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0038_categoryrequest_review_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='info',
            field=models.TextField(blank=True, help_text='Displayed on the category page. Limited use of HTML is allowed. Supports Markdown.', null=True),
        ),
    ]
