# Generated by Django 3.0.9 on 2020-08-10 15:35

import django.core.validators
from django.db import migrations, models
import racetime.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0038_categoryrequest_review_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(db_index=True, help_text='Who you want to be known as on the site (3-25 characters).', max_length=25, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(inverse_match=True, message='Name cannot contain @ or #', regex='[\\x00@#]'), racetime.models.user.UsernameValidator()]),
        ),
    ]
