# Generated by Django 3.0.9 on 2020-08-10 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0040_category_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_moderators',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='category',
            name='max_owners',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('activate', 'set category to active'), ('deactivate', 'set category to inactive'), ('name_change', 'updated category name'), ('short_name_change', 'updated category short name'), ('image_change', 'updated category image'), ('info_change', 'updated category info'), ('slug_words_change', 'updated category slug words'), ('streaming_required_change', 'updated category streaming requirement'), ('allow_stream_override_change', 'updated category stream override'), ('owner_add', 'added a owner'), ('owner_remove', 'removed a owner'), ('moderator_add', 'added a moderator'), ('moderator_remove', 'removed a moderator'), ('bot_add', 'added a bot'), ('bot_activate', 're-activated a bot'), ('bot_deactivate', 'deactivated a bot'), ('goal_add', 'added a new goal'), ('goal_activate', 're-activated a goal'), ('goal_deactivate', 'deactivated a goal'), ('goal_rename', 'renamed a goal'), ('owner_change', 'transferred category ownership')], db_index=True, max_length=255),
        ),
    ]
