# Generated by Django 3.0.7 on 2020-08-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0042_user_twitch_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='allow_unlisted',
            field=models.BooleanField(default=False, help_text='Allow users to create unlisted race rooms in this category (moderators can always do this).', verbose_name='Allow unlisted races'),
        ),
        migrations.AddField(
            model_name='category',
            name='allow_user_races',
            field=models.BooleanField(default=True, help_text='Allow users to create start races. If disabled, only category moderators will be allowed to start a race.'),
        ),
        migrations.AddField(
            model_name='category',
            name='unlisted_by_default',
            field=models.BooleanField(default=False, help_text='Races in this category will be unlisted by default, assuming the user starting the race has permission to create an unlisted race.'),
        ),
        migrations.AddField(
            model_name='race',
            name='unlisted',
            field=models.BooleanField(db_index=True, default=False, help_text='Hide this race from the category page, meaning only people with the direct link can find it. Unlisted races will be made visible when the room closes.'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('activate', 'set category to active'), ('deactivate', 'set category to inactive'), ('name_change', 'updated category name'), ('short_name_change', 'updated category short name'), ('image_change', 'updated category image'), ('info_change', 'updated category info'), ('slug_words_change', 'updated category slug words'), ('streaming_required_change', 'updated category streaming requirement'), ('allow_stream_override_change', 'updated category stream override'), ('allow_unlisted_change', 'updated unlisted races user permission'), ('owner_add', 'added a owner'), ('owner_remove', 'removed a owner'), ('moderator_add', 'added a moderator'), ('moderator_remove', 'removed a moderator'), ('bot_add', 'added a bot'), ('bot_activate', 're-activated a bot'), ('bot_deactivate', 'deactivated a bot'), ('goal_add', 'added a new goal'), ('goal_activate', 're-activated a goal'), ('goal_deactivate', 'deactivated a goal'), ('goal_rename', 'renamed a goal'), ('owner_change', 'transferred category ownership')], db_index=True, max_length=255),
        ),
    ]
