# Generated by Django 3.0.9 on 2020-11-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0045_remove_misc_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='auto_start',
            field=models.BooleanField(default=True, help_text='Begin the race as soon as everyone is ready. If disabled, a race monitor must use the "Force start" action to begin the race.', verbose_name='Auto-start'),
        ),
        migrations.AlterField(
            model_name='race',
            name='allow_non_entrant_chat',
            field=models.BooleanField(default=True, help_text='Allow users who are not entered in the race to chat while the race is in progress (anyone may use chat before and after the race).', verbose_name='Allow non-entrant chat'),
        ),
    ]
