# Generated by Django 3.0.9 on 2020-11-07 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0046_auto_20201107_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_bots',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='category',
            name='max_goals',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
