# Generated by Django 3.0.11 on 2020-11-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0047_auto_20201107_1531'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entrant',
            index=models.Index(fields=['race', 'state'], name='racetime_en_race_id_75338f_idx'),
        ),
        migrations.AddIndex(
            model_name='entrant',
            index=models.Index(fields=['race', 'state', 'dnf', 'dq'], name='racetime_en_race_id_1741ee_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['race', 'deleted'], name='racetime_me_race_id_d38bb5_idx'),
        ),
    ]
