# Generated by Django 3.0.11 on 2020-11-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0049_race_hide_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrant',
            name='rating',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='rating_change',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='bot_pid',
            field=models.PositiveIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='userranking',
            name='rating',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='userranking',
            name='times_raced',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
