# Generated by Django 3.0.11 on 2021-01-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0051_auto_20201215_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='search_name',
            field=models.CharField(blank=True, db_index=True, help_text='A searchable name for the category, e.g. "Pokemon Emerald".', max_length=255),
        ),
    ]
