# Generated by Django 3.0.11 on 2020-12-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0051_auto_20201215_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='archived',
            field=models.BooleanField(default=False, help_text='Archive the race, preventing new races from being made in this category and moves the category to a separate section.'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('activate', 'set category to active'), ('deactivate', 'set category to inactive'), ('archived', 'archived the category'), ('restore', 'restored the category'), ('name_change', 'updated category name'), ('short_name_change', 'updated category short name'), ('search_name_change', 'updated category search name'), ('image_change', 'updated category image'), ('info_change', 'updated category info'), ('slug_words_change', 'updated category slug words'), ('streaming_required_change', 'updated category streaming requirement'), ('allow_stream_override_change', 'updated category stream override'), ('allow_unlisted_change', 'updated unlisted races user permission'), ('owner_add', 'added a owner'), ('owner_remove', 'removed a owner'), ('moderator_add', 'added a moderator'), ('moderator_remove', 'removed a moderator'), ('bot_add', 'added a bot'), ('bot_activate', 're-activated a bot'), ('bot_deactivate', 'deactivated a bot'), ('goal_add', 'added a new goal'), ('goal_activate', 're-activated a goal'), ('goal_deactivate', 'deactivated a goal'), ('goal_rename', 'renamed a goal'), ('owner_change', 'transferred category ownership')], db_index=True, max_length=255),
        ),
    ]
