# Generated by Django 3.0.11 on 2020-12-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0051_category_search_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='search_names',
        ),
        migrations.AddField(
            model_name='category',
            name='search_name',
            field=models.CharField(db_index=True, default='', help_text='A searchable name for the category, e.g. "Pokemon Emerald".', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='The full name of this category, e.g. "Pokémon Emerald".', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='short_name',
            field=models.CharField(db_index=True, help_text='An abbreviation or other short identifier, e.g. "PKMNE".', max_length=16),
        ),
    ]
