# Generated by Django 3.0.11 on 2020-12-22 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0053_auto_20201218_0217'),
        ('racetime', '0053_auto_20201222_0444'),
    ]

    operations = [
    ]
