# Generated by Django 3.0.13 on 2021-04-04 17:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import racetime.validators


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0053_auto_20210404_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrant',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='racetime.Team'),
        ),
        migrations.AddField(
            model_name='race',
            name='require_even_teams',
            field=models.BooleanField(default=False, help_text='Require all teams to have an equal number of participants before the race can start (only applies to team races).'),
        ),
        migrations.AddField(
            model_name='race',
            name='team_race',
            field=models.BooleanField(db_index=True, default=False, help_text='Create a team race. Entrants will need to join a team to participate.'),
        ),
        migrations.AddField(
            model_name='team',
            name='formal',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='The name of your team. Must be unique and follow our naming guidelines.', max_length=50, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(inverse_match=True, message='Name cannot contain @ or #', regex='[\\x00@#]'), racetime.validators.UsernameValidator()]),
        ),
    ]
