# Generated by Django 3.0.14 on 2021-04-26 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0054_auto_20210404_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(help_text='Forms part of the URL of your team page, e.g. "your-team" will give "racetime.gg/team/your-team". Slug must be unique, and can only use letters, numbers and hyphens. You cannot change this later.', unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
