# Generated by Django 3.0.14 on 2021-08-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0055_auto_20210426_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pronouns',
            field=models.CharField(blank=True, choices=[('', 'none'), ('she/her', 'she/her'), ('he/him', 'he/him'), ('they/them', 'they/them'), ('she/they', 'she/they'), ('he/they', 'he/they'), ('other/ask!', 'other/ask!')], help_text='Select which pronouns appear next to your name on the site.', max_length=16, null=True),
        ),
    ]
