# Generated by Django 3.0.14 on 2022-02-16 18:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0057_auto_20220216_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_emotes',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.CreateModel(
            name='Emote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Must be one word with camel-case, e.g. "PogChamp".', max_length=16)),
                ('image', models.ImageField(help_text='Recommended size: 56x56. Keep file size small as possible.', upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racetime.Category')),
            ],
        ),
    ]
