# Generated by Django 3.0.14 on 2022-02-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0058_auto_20220216_1815'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='emote',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_emote_category_name'),
        ),
    ]
