# Generated by Django 3.0.14 on 2022-04-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0059_auto_20220216_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='time_limit_auto_complete',
            field=models.BooleanField(default=False, help_text='Complete the race instead of canceling it if the time limit is reached with no finishers.', verbose_name='Time limit auto-complete'),
        ),
    ]
