# Generated by Django 3.2.19 on 2023-10-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0064_auto_20230904_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='The full name of this category, e.g. "Pokémon Emerald".', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='search_name',
            field=models.CharField(blank=True, db_index=True, help_text='A searchable name for the category, e.g. "Pokemon Emerald".', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(help_text='A unique identifier for this category used in the URL, e.g. "tetris-99".', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='categoryrequest',
            name='goals',
            field=models.TextField(default='Beat the game', help_text='Add goals, one per line, that people can race against. Goal names should be short, clear and simple, e.g. "Any%", "16 stars", or simply "Beat the game". You can add more goals later, but your category must have at least one goal to start with.'),
        ),
        migrations.AlterField(
            model_name='categoryrequest',
            name='name',
            field=models.CharField(help_text='The full name of this category, e.g. "Super Mario 64" or "Multiple Sonic Games".', max_length=100),
        ),
        migrations.AlterField(
            model_name='categoryrequest',
            name='slug',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.CharField(help_text='The win conditions for the race, e.g. "16 stars".', max_length=100),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['race', 'deleted', 'pinned'], name='racetime_me_race_id_ca500e_idx'),
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='racetime_me_race_id_d38bb5_idx',
        ),
    ]
