# Generated by Django 3.2.19 on 2023-10-11 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0065_auto_20231001_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='direct_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
