# Generated by Django 3.2.19 on 2024-08-04 09:29

import django.core.validators
from django.db import migrations, models
import racetime.validators


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0066_auto_20231011_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(db_index=True, help_text='The name of your team. Must be unique and follow our naming guidelines.', max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(inverse_match=True, message='Name cannot contain @ or #', regex='[\\x00@#]'), racetime.validators.UsernameValidator()]),
        ),
    ]
