# Generated by Django 3.2.19 on 2024-08-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0069_auto_20240808_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patreon_id',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='patreon_name',
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
    ]
