# Generated by Django 3.2.19 on 2025-03-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0074_auto_20250323_1347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupporterSchedule',
        ),
    ]
