# Generated by Django 3.2.19 on 2025-04-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0075_delete_supporterschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='allow_hide_entrants',
            field=models.BooleanField(default=False, help_text='<strong>Beta:</strong> Allow races in this category to be anonymised <a href="https://github.com/racetimeGG/racetime-app/wiki/Category-management-and-moderation#beta-features" target="_blank">(read more)</a>', verbose_name='Allow hidden entrants'),
        ),
        migrations.AddField(
            model_name='category',
            name='allow_partitionable',
            field=models.BooleanField(default=False, help_text='<strong>Beta:</strong> Allow users to create 1v1 ladder races <a href="https://github.com/racetimeGG/racetime-app/wiki/Category-management-and-moderation#beta-features" target="_blank">(read more)</a>', verbose_name='Allow 1v1 ladder races'),
        ),
        migrations.AddField(
            model_name='race',
            name='disqualify_unready',
            field=models.BooleanField(default=False, help_text='When the race starts, entrants that have not readied up are DQed instead of removed. Also prevents entrants from quitting.'),
        ),
        migrations.AddField(
            model_name='race',
            name='hide_entrants',
            field=models.BooleanField(default=False, help_text='Hide entrant identities until the race is finished. <strong>Pre-race and mid-race chat will be disabled.</strong>'),
        ),
        migrations.AddField(
            model_name='race',
            name='partitionable',
            field=models.BooleanField(default=False, help_text='Before the race begins, partition entrants into separate, anonymised 1v1 race rooms.', verbose_name='1v1 ladder race'),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='state',
            field=models.CharField(choices=[('requested', 'Requesting to join'), ('invited', 'Invited to join'), ('declined', 'Declined invitation'), ('joined', 'Joined'), ('partitioned', 'Partitioned')], default='joined', max_length=50),
        ),
        migrations.AlterField(
            model_name='race',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('invitational', 'Invitational'), ('pending', 'Getting ready'), ('in_progress', 'In progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('partitioned', 'Partitioned')], default='open', max_length=50),
        ),
    ]
