# Generated by Django 3.2.19 on 2025-04-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0076_auto_20250421_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='hold',
            field=models.BooleanField(default=False, help_text='Temporarily prevents race from being recorded when enabled.'),
        ),
    ]
