# Generated by Django 3.2.19 on 2025-01-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0077_race_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='opened_by_bot',
            field=models.CharField(
                max_length=25,
                null=True,
                blank=True,
                help_text='Name of the bot that opened this race, if any.',
            ),
        ),
    ] 