# Generated by Django 5.2.5 on 2025-08-18 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0077_race_hold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='monitors',
            field=models.ManyToManyField(blank=True, help_text='Set users (other than yourself) who can monitor this race (category owner and moderators can always monitor races).', related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='favourite_categories',
            field=models.ManyToManyField(blank=True, limit_choices_to={'active': True}, related_name='+', to='racetime.category'),
        ),
    ]
