# Generated by Django 5.2.5 on 2025-08-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0078_alter_race_monitors_alter_user_favourite_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='bot_meta',
            field=models.JSONField(default=dict),
        ),
    ]
