# Generated by Django 3.2.19 on 2025-01-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0078_add_opened_by_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='reveal_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When this hidden unranked race should be revealed. Only applies to unlisted races that are not recordable.',
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name='race',
            index=models.Index(
                fields=['unlisted', 'recordable', 'reveal_at'],
                name='reveal_hidden_races_idx',
            ),
        ),
    ] 