# Generated by Django 5.2.5 on 2025-08-28 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0078_add_opened_by_bot'),
        ('racetime', '0079_race_bot_meta'),
    ]

    operations = [
    ]
