# Generated by Django 5.2.5 on 2025-08-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0080_merge_0078_add_opened_by_bot_0079_race_bot_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='bot_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
