# Generated by Django 5.2.7 on 2025-10-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0082_add_youtube_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='youtube_code',
            field=models.JSONField(editable=False, help_text='YouTube OAuth token data (JSON)', null=True),
        ),
    ]
