# Generated by Django 5.2.7 on 2025-10-31 00:38

from django.db import migrations, models


def populate_platform_fields(apps, schema_editor):
    """
    Populate the new platform-specific stream fields based on existing stream_live data.
    
    For existing entrants with stream_live=True, we'll need to check which platform(s)
    they have and set the fields accordingly. Since we can't determine which specific
    platform was live historically, we'll reset all fields to False and let the
    RaceBot update them correctly on the next check.
    """
    Entrant = apps.get_model('racetime', 'Entrant')
    
    # Reset all platform-specific fields to False
    # The RaceBot will update them correctly on the next polling cycle
    Entrant.objects.all().update(twitch_live=False, youtube_live=False)


def reverse_populate_platform_fields(apps, schema_editor):
    """
    Reverse migration - this is safe since we're just resetting fields.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0083_alter_user_youtube_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrant',
            name='twitch_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entrant',
            name='youtube_live',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            populate_platform_fields,
            reverse_populate_platform_fields,
        ),
    ]
