from django.urls import path, include
from oauth2_provider import views as oauth2_views

from . import views

urlpatterns = [
    path('account', views.EditAccount.as_view(), name='edit_account'),
    path('account/', include([
        path('auth', views.LoginRegister.as_view(), name='login_or_register'),
        path('connections', views.EditAccountConnections.as_view(), name='edit_account_connections'),
        path('security', views.EditAccountSecurity.as_view(), name='edit_account_security'),
        path('standing', views.AccountStanding.as_view(), name='account_standing'),
        path('teams', views.EditAccountTeams.as_view(), name='edit_account_teams'),
        path('teams/create', views.CreateTeam.as_view(), name='create_team'),
        path('teams/join/<str:team>', views.JoinTeam.as_view(), name='join_team'),
        path('teams/leave/<str:team>', views.LeaveTeam.as_view(), name='leave_team'),
        path('login', views.Login.as_view(), name='login'),
        path('logout', views.Logout.as_view(), name='logout'),
        path('create', views.CreateAccount.as_view(), name='create_account'),
        path('twitch_auth', views.TwitchAuth.as_view(), name='twitch_auth'),
        path('twitch_disconnect', views.TwitchDisconnect.as_view(), name='twitch_disconnect'),
        path('derp', views.PasswordResetView.as_view(), name='password_reset'),
        path('derp/done', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
        path('reset/<uidb64>/<token>', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
        path('reset/complete', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    ])),

    path('o/', include([
        path('authorize', views.OAuthAuthorize.as_view(), name='oauth2_authorize'),
        path('token', oauth2_views.TokenView.as_view(), name='oauth2_token'),
        path('revoke_token', oauth2_views.RevokeTokenView.as_view(), name='oauth2_revoke'),

        path('delete/<pk>', views.OAuthDeleteToken.as_view(), name='oauth2_delete'),
        path('done', views.OAuthDone.as_view(), name='oauth2_authorize_done'),
        path('userinfo', views.OAuthUserInfo.as_view(), name='oauth2_userinfo'),
        path('<str:category>/startrace', views.OAuthCreateRace.as_view(), name='oauth2_create_race'),
        path('<str:category>/<str:race>/edit', views.OAuthEditRace.as_view(), name='oauth2_edit_race'),
        path('<str:category>/<str:race>/monitor/pin/<str:message>', views.OAuthRaceChatPin.as_view(), name='oauth2_chat_pin'),
        path('<str:category>/<str:race>/monitor/unpin/<str:message>', views.OAuthRaceChatUnpin.as_view(), name='oauth2_chat_unpin'),
        path('<str:category>/<str:race>/monitor/purge/<str:message>', views.OAuthRaceChatPurge.as_view(), name='oauth2_chat_purge'),
        path('<str:category>/<str:race>/monitor/delete/<str:message>', views.OAuthRaceChatDelete.as_view(), name='oauth2_chat_delete'),
    ])),

    path('team/', include([
        path('<str:team>.json', views.TeamData.as_view()),
        path('<str:team>', views.Team.as_view(), name='team'),
        path('<str:team>/', include([
            path('data', views.TeamData.as_view(), name='team_data'),
            path('manage/', include([
                path('edit', views.EditTeam.as_view(), name='edit_team'),
                path('delete', views.DeleteTeam.as_view(), name='delete_team'),
                path('members', views.TeamMembers.as_view(), name='team_members'),
                path('members/add', views.AddTeamMember.as_view(), name='team_member_add'),
                path('members/remove', views.RemoveTeamMember.as_view(), name='team_member_remove'),
                path('members/add-owner', views.AddTeamOwner.as_view(), name='team_owner_add'),
                path('members/remove-owner', views.RemoveTeamOwner.as_view(), name='team_owner_remove'),
                path('log', views.TeamAudit.as_view(), name='team_audit_log'),
            ])),
        ])),
    ])),

    path('autocomplete/', include([
        path('user', views.AutocompleteUser.as_view(), name='autocomplete_user'),
    ])),

    path('', views.Home.as_view(), name='home'),
    path('search', views.Search.as_view(), name='search'),
    path('request_category', views.RequestCategory.as_view(), name='request_category'),
    path('races/data', views.RaceListData.as_view(), name='race_list_data'),
    path('races.json', views.RaceListData.as_view()),
    path('user/search', views.AutocompleteUser.as_view(), name='autocomplete_user'),
    path('user/<str:user>', views.ViewProfile.as_view(), name='view_profile'),
    path('user/<str:user>.json', views.UserProfileData.as_view()),
    path('user/<str:user>/', include([
        path('data', views.UserProfileData.as_view(), name='user_profile_data'),
        path('races/data', views.UserRaceData.as_view(), name='user_race_list_data'),
        path('races.json', views.UserRaceData.as_view()),
    ])),

    path('categories/data', views.CategoryListData.as_view(), name='category_list_data'),
    path('<str:category>.json', views.CategoryData.as_view()),
    path('<str:category>', views.Category.as_view(), name='category'),
    path('<str:category>/', include([
        path('data', views.CategoryData.as_view(), name='category_data'),
        path('races/data', views.CategoryRaceData.as_view(), name='category_race_list_data'),
        path('races.json', views.CategoryRaceData.as_view()),
        path('manage/', include([
            path('edit', views.EditCategory.as_view(), name='edit_category'),
            path('deactivate', views.DeactivateCategory.as_view(), name='category_deactivate'),
            path('reactivate', views.ReactivateCategory.as_view(), name='category_reactivate'),
            path('goals', views.GoalList.as_view(), name='category_goals'),
            path('goals/new', views.CreateGoal.as_view(), name='new_category_goal'),
            path('goals/<str:goal>/edit', views.EditGoal.as_view(), name='edit_category_goal'),
            path('bots', views.BotList.as_view(), name='category_bots'),
            path('bots/new', views.CreateBot.as_view(), name='new_category_bot'),
            path('bots/<str:bot>/deactivate', views.DeactivateBot.as_view(), name='deactivate_category_bot'),
            path('bots/<str:bot>/reactivate', views.ReactivateBot.as_view(), name='reactivate_category_bot'),
            path('mods', views.CategoryModerators.as_view(), name='category_mods'),
            path('mods/add_owner', views.AddOwner.as_view(), name='category_owners_add'),
            path('mods/remove_owner', views.RemoveOwner.as_view(), name='category_owners_remove'),
            path('mods/add_moderator', views.AddModerator.as_view(), name='category_mods_add'),
            path('mods/remove_moderator', views.RemoveModerator.as_view(), name='category_mods_remove'),
            path('teams', views.CategoryTeams.as_view(), name='category_teams'),
            path('log', views.CategoryAudit.as_view(), name='category_audit_log'),
            path('emotes', views.CategoryManageEmotes.as_view(), name='category_emotes'),
            path('emotes/add', views.AddEmote.as_view(), name='category_emotes_add'),
            path('emotes/<str:emote_name>/remove', views.RemoveEmote.as_view(), name='category_emotes_remove'),
        ])),
        path('leaderboards', views.CategoryLeaderboards.as_view(), name='leaderboards'),
        path('leaderboards/data', views.CategoryLeaderboardsData.as_view(), name='leaderboards_data'),
        path('leaderboards.json', views.CategoryLeaderboardsData.as_view()),
        path('emotes', views.CategoryEmotes.as_view(), name='category_list_emotes'),
        path('startrace', views.CreateRace.as_view(), name='create_race'),
        path('star', views.FavouriteCategory.as_view(), name='star'),
        path('unstar', views.UnfavouriteCategory.as_view(), name='unstar'),
    ])),

    path('<str:category>/<str:race>.csv', views.RaceCSV.as_view()),
    path('<str:category>/<str:race>.json', views.RaceData.as_view()),
    path('<str:category>/<str:race>.log', views.RaceChatLog.as_view()),
    path('<str:category>/<str:race>.txt', views.RaceChatLog.as_view()),
    path('<str:category>/<str:race>', views.Race.as_view(), name='race'),
    path('<str:category>/<str:race>/', include([
        path('csv', views.RaceCSV.as_view(), name='race_csv'),
        path('data', views.RaceData.as_view(), name='race_data'),
        path('mini', views.RaceMini.as_view(), name='race_mini'),
        path('livesplit', views.RaceLiveSplit.as_view(), name='race_livesplit'),
        path('log', views.RaceChatLog.as_view(), name='race_log'),
        path('renders', views.RaceRenders.as_view(), name='race_renders'),
        path('spectate', views.RaceSpectate.as_view(), name='race_spectate'),

        path('message', views.Message.as_view(), name='message'),
        path('join', views.Join.as_view(), name='join'),
        path('leave', views.Leave.as_view(), name='leave'),
        path('request_invite', views.RequestInvite.as_view(), name='request_invite'),
        path('cancel_invite', views.CancelInvite.as_view(), name='cancel_invite'),
        path('accept_invite', views.AcceptInvite.as_view(), name='accept_invite'),
        path('decline_invite', views.DeclineInvite.as_view(), name='decline_invite'),
        path('ready', views.Ready.as_view(), name='ready'),
        path('unready', views.Unready.as_view(), name='unready'),
        path('done', views.Done.as_view(), name='done'),
        path('undone', views.Undone.as_view(), name='undone'),
        path('split', views.Split.as_view(), name='split'),
        path('forfeit', views.Forfeit.as_view(), name='forfeit'),
        path('unforfeit', views.Unforfeit.as_view(), name='unforfeit'),
        path('add_comment', views.AddComment.as_view(), name='add_comment'),
        path('add_comment', views.AddComment.as_view(), name='change_comment'),
        path('set_team', views.SetTeam.as_view(), name='set_team'),
        path('available_teams', views.RaceAvailableTeams.as_view(), name='available_teams'),

        path('monitor/', include([
            path('edit', views.EditRace.as_view(), name='edit_race'),
            path('open', views.MakeOpen.as_view(), name='make_open'),
            path('invitational', views.MakeInvitational.as_view(), name='make_invitational'),
            path('begin', views.BeginRace.as_view(), name='begin_race'),
            path('cancel', views.CancelRace.as_view(), name='cancel_race'),
            path('invite', views.InviteToRace.as_view(), name='invite_to_race'),
            path('record', views.RecordRace.as_view(), name='record_race'),
            path('unrecord', views.UnrecordRace.as_view(), name='unrecord_race'),
            path('rematch', views.Rematch.as_view(), name='rematch'),
            path('pin/<str:message>', views.RaceChatPin.as_view(), name='chat_pin'),
            path('unpin/<str:message>', views.RaceChatUnpin.as_view(), name='chat_unpin'),
            path('delete/<str:message>', views.RaceChatDelete.as_view(), name='chat_delete'),
            path('purge/<str:message>', views.RaceChatPurge.as_view(), name='chat_purge'),

            path('<str:entrant>/', include([
                path('edit', views.EditRaceResult.as_view(), name='edit_race_result'),
                path('accept_request', views.AcceptRequest.as_view(), name='accept_request'),
                path('force_unready', views.ForceUnready.as_view(), name='force_unready'),
                path('override_stream', views.OverrideStream.as_view(), name='override_stream'),
                path('remove', views.Remove.as_view(), name='remove'),
                path('disqualify', views.Disqualify.as_view(), name='disqualify'),
                path('undisqualify', views.Undisqualify.as_view(), name='undisqualify'),
                path('add_monitor', views.AddMonitor.as_view(), name='add_monitor'),
                path('remove_monitor', views.RemoveMonitor.as_view(), name='remove_monitor'),
            ])),
        ])),
    ])),
]
